[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
memos = "6e3aABH3MD1DzDy86CdJefjt1qa2QsJxwDxMHu6iNigy"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
